2011/11/13 19:07:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\xampp\htdocs\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(54): CModule->__get('db')
#5 C:\xampp\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('gii/model')
#14 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/mybook/index.php?r=gii/model
2011/11/13 19:09:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php:364
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php(313): CDbConnection->open()
#1 C:\xampp\xampp\htdocs\yii\framework\db\CDbConnection.php(291): CDbConnection->setActive(true)
#2 C:\xampp\xampp\htdocs\yii\framework\base\CModule.php(372): CDbConnection->init()
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModule.php(86): CModule->getComponent('db')
#4 C:\xampp\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(54): CModule->__get('db')
#5 C:\xampp\xampp\htdocs\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 C:\xampp\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(149): CFormModel->__construct()
#7 C:\xampp\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(61): CCodeGenerator->prepare()
#8 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('gii/model')
#14 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/mybook/index.php?r=gii/model
2011/11/13 19:25:35 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE LOWER(username)=? LIMIT 1.
in C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php (14)
in C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php (52)
in C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php (88)
2011/11/13 19:25:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'. The SQL statement executed was: SELECT * FROM `user` `t` WHERE LOWER(username)=? LIMIT 1' in C:\xampp\xampp\htdocs\yii\framework\db\CDbCommand.php:516
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\CDbCommand.php(393): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1290): CDbCommand->queryRow()
#2 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1396): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(14): CActiveRecord->find('LOWER(username)...', Array)
#4 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#6 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#9 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#12 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#14 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#15 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#16 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#17 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:26:09 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_name" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(13): CComponent->__get('user_name')
#1 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:28:03 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_name" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(13): CComponent->__get('user_name')
#1 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:28:48 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_name" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(13): CComponent->__get('user_name')
#1 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:29:03 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_name" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(13): CComponent->__get('user_name')
#1 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:37:15 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('id')
#1 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(20): CActiveRecord->__get('id')
#2 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#4 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#12 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#13 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:37:43 [error] [exception.CException] exception 'CException' with message 'Property "User.username" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('username')
#1 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(21): CActiveRecord->__get('username')
#2 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#4 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#7 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#12 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#13 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#14 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#15 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 19:38:16 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_id" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\xampp\htdocs\mybook\protected\components\UserIdentity.php(20): CComponent->__set('user_id', '1')
#1 C:\xampp\xampp\htdocs\mybook\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): LoginForm->authenticate('password', Array)
#3 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\SiteController.php(88): CModel->validate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('login')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/login')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=site/login
2011/11/13 21:26:15 [error] [php] YiiBase::include(normalizeTags.php) [<a href='function.YiiBase-include'>function.YiiBase-include</a>]: failed to open stream: No such file or directory (C:\xampp\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(166): import()
#1 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(283): createValidator()
#2 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(257): Book->createValidators()
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(301): Book->getValidators()
#4 C:\xampp\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1179): Book->isAttributeRequired()
#5 C:\xampp\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(553): activeLabelEx()
#6 C:\xampp\xampp\htdocs\mybook\protected\views\book\_form.php(13): CActiveForm->labelEx()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#8 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#10 C:\xampp\xampp\htdocs\mybook\protected\views\book\create.php(15): BookController->renderPartial()
#11 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#12 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(779): BookController->renderPartial()
#15 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(68): BookController->render()
#16 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#17 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#18 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): BookController->runAction()
#19 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#20 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CAccessControlFilter->filter()
#21 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): BookController->filterAccessControl()
#22 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#23 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#24 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): BookController->runActionWithFilters()
#25 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): BookController->run()
#26 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#27 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#28 C:\xampp\xampp\htdocs\mybook\index.php(13): CWebApplication->run()
REQUEST_URI=/mybook/index.php?r=book/create
in C:\xampp\xampp\htdocs\mybook\protected\views\book\_form.php (13)
in C:\xampp\xampp\htdocs\mybook\protected\views\book\create.php (15)
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (68)
2011/11/13 21:27:39 [error] [php] YiiBase::include(normalizeTags.php) [<a href='function.YiiBase-include'>function.YiiBase-include</a>]: failed to open stream: No such file or directory (C:\xampp\xampp\htdocs\yii\framework\YiiBase.php:421)
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(166): import()
#1 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(283): createValidator()
#2 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(257): Book->createValidators()
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(301): Book->getValidators()
#4 C:\xampp\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1179): Book->isAttributeRequired()
#5 C:\xampp\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(553): activeLabelEx()
#6 C:\xampp\xampp\htdocs\mybook\protected\views\book\_form.php(13): CActiveForm->labelEx()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#8 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#10 C:\xampp\xampp\htdocs\mybook\protected\views\book\create.php(15): BookController->renderPartial()
#11 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#12 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(779): BookController->renderPartial()
#15 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(68): BookController->render()
#16 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#17 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#18 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): BookController->runAction()
#19 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#20 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CAccessControlFilter->filter()
#21 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): BookController->filterAccessControl()
#22 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#23 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#24 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): BookController->runActionWithFilters()
#25 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): BookController->run()
#26 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#27 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#28 C:\xampp\xampp\htdocs\mybook\index.php(13): CWebApplication->run()
REQUEST_URI=/mybook/index.php?r=book/create
in C:\xampp\xampp\htdocs\mybook\protected\views\book\_form.php (13)
in C:\xampp\xampp\htdocs\mybook\protected\views\book\create.php (15)
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (68)
2011/11/13 21:29:45 [warning] [application] Failed to set unsafe attribute "book_title" of "Book".
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (61)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/13 21:29:45 [warning] [application] Failed to set unsafe attribute "book_tags" of "Book".
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (61)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/13 21:29:45 [error] [exception.CException] exception 'CException' with message 'Property "Book.title" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('title')
#1 C:\xampp\xampp\htdocs\yii\framework\validators\CRequiredValidator.php(46): CActiveRecord->__get('title')
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CRequiredValidator->validateAttribute(Object(Book), 'title')
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(Book), NULL)
#4 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(780): CModel->validate(NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(62): CActiveRecord->save()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('create')
#16 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/create')
#17 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#18 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#19 {main} REQUEST_URI=/mybook/index.php?r=book/create
2011/11/13 21:33:11 [warning] [application] Failed to set unsafe attribute "book_title" of "Book".
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (61)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/13 21:33:11 [warning] [application] Failed to set unsafe attribute "book_tags" of "Book".
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (61)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/13 21:33:11 [error] [exception.CException] exception 'CException' with message 'Property "Book.title" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('title')
#1 C:\xampp\xampp\htdocs\yii\framework\validators\CRequiredValidator.php(46): CActiveRecord->__get('title')
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CRequiredValidator->validateAttribute(Object(Book), 'title')
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(Book), NULL)
#4 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(780): CModel->validate(NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(62): CActiveRecord->save()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('create')
#16 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/create')
#17 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#18 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#19 {main} REQUEST_URI=/mybook/index.php?r=book/create
2011/11/13 21:35:20 [warning] [application] Failed to set unsafe attribute "book_tags" of "Book".
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (61)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/13 21:35:20 [error] [exception.CException] exception 'CException' with message 'Property "Book.tags" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('tags')
#1 C:\xampp\xampp\htdocs\yii\framework\validators\CRegularExpressionValidator.php(46): CActiveRecord->__get('tags')
#2 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CRegularExpressionValidator->validateAttribute(Object(Book), 'tags')
#3 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(Book), NULL)
#4 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(780): CModel->validate(NULL)
#5 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(62): CActiveRecord->save()
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('create')
#16 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/create')
#17 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#18 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#19 {main} REQUEST_URI=/mybook/index.php?r=book/create
2011/11/13 21:39:06 [error] [exception.CException] exception 'CException' with message 'Property "Book.update_time" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:174
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__set('update_time', 1321216746)
#1 C:\xampp\xampp\htdocs\mybook\protected\models\Book.php(100): CActiveRecord->__set('update_time', 1321216746)
#2 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1011): Book->beforeSave()
#3 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(781): CActiveRecord->insert(NULL)
#4 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(62): CActiveRecord->save()
#5 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#6 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#7 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#8 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#10 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#11 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#12 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#13 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('create')
#15 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/create')
#16 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#17 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#18 {main} REQUEST_URI=/mybook/index.php?r=book/create
2011/11/15 10:45:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "book".' in C:\xampp\xampp\htdocs\yii\framework\web\CController.php:477
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(262): CController->missingAction('book')
#1 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('book')
#2 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('site/book')
#3 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#4 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#5 {main} REQUEST_URI=/mybook/index.php?r=site/book&0=index
2011/11/15 11:23:00 [error] [exception.CException] exception 'CException' with message 'Property "Book.book_short_description" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('book_short_desc...')
#1 C:\xampp\xampp\htdocs\yii\framework\web\helpers\CHtml.php(2063): CActiveRecord->__get('book_short_desc...')
#2 C:\xampp\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1252): CHtml::resolveValue(Object(Book), 'book_short_desc...')
#3 C:\xampp\xampp\htdocs\yii\framework\web\widgets\CActiveForm.php(613): CHtml::activeTextArea(Object(Book), 'book_short_desc...', Array)
#4 C:\xampp\xampp\htdocs\mybook\protected\views\book\_form.php(20): CActiveForm->textArea(Object(Book), 'book_short_desc...', Array)
#5 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('C:\xampp\xampp\...')
#6 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\xampp\...', Array, true)
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\xampp\...', Array, true)
#8 C:\xampp\xampp\htdocs\mybook\protected\views\book\create.php(15): CController->renderPartial('_form', Array)
#9 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('C:\xampp\xampp\...')
#10 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\xampp\...', Array, true)
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\xampp\...', Array, true)
#12 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(779): CController->renderPartial('create', Array, true)
#13 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(68): CController->render('create', Array)
#14 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionCreate()
#15 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#16 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#17 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#18 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#22 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('create')
#24 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/create')
#25 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#26 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#27 {main} REQUEST_URI=/mybook/index.php?r=book/create
2011/11/15 11:45:57 [error] [exception.CException] exception 'CException' with message 'Property "Book.book_creation_time" is not defined.' in C:\xampp\xampp\htdocs\yii\framework\base\CComponent.php:131
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(129): CComponent->__get('book_creation_t...')
#1 C:\xampp\xampp\htdocs\mybook\protected\views\book\_view.php(11): CActiveRecord->__get('book_creation_t...')
#2 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('C:\xampp\xampp\...')
#3 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\xampp\...', Array, true)
#4 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\xampp\...', Array, true)
#5 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CListView.php(242): CController->renderPartial('_view', Array)
#6 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(158): CListView->renderItems()
#7 [internal function]: CBaseListView->renderSection(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(141): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#9 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(126): CBaseListView->renderContent()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(166): CBaseListView->run()
#11 C:\xampp\xampp\htdocs\mybook\protected\views\book\index.php(17): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require('C:\xampp\xampp\...')
#13 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): CBaseController->renderInternal('C:\xampp\xampp\...', Array, true)
#14 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): CBaseController->renderFile('C:\xampp\xampp\...', Array, true)
#15 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(779): CController->renderPartial('index', Array, true)
#16 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(118): CController->render('index', Array)
#17 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionIndex()
#18 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#19 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#20 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#21 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#25 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('index')
#27 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('book/index')
#28 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#29 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#30 {main} REQUEST_URI=/mybook/index.php?r=book/index
2011/11/15 11:46:54 [error] [php] date() expects parameter 2 to be long, string given (C:\xampp\xampp\htdocs\mybook\protected\views\book\_view.php:11)
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#1 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#2 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CListView.php(242): BookController->renderPartial()
#3 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(158): CListView->renderItems()
#4 unknown(0): CListView->renderSection()
#5 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(141): preg_replace_callback()
#6 C:\xampp\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(126): CListView->renderContent()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(166): CListView->run()
#8 C:\xampp\xampp\htdocs\mybook\protected\views\book\index.php(17): BookController->widget()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(119): require()
#10 C:\xampp\xampp\htdocs\yii\framework\web\CBaseController.php(88): BookController->renderInternal()
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(866): BookController->renderFile()
#12 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(779): BookController->renderPartial()
#13 C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php(118): BookController->render()
#14 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): BookController->actionIndex()
#15 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#16 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): BookController->runAction()
#17 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#18 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(1144): CAccessControlFilter->filter()
#19 C:\xampp\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): BookController->filterAccessControl()
#20 C:\xampp\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#21 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(283): CFilterChain->run()
#22 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): BookController->runActionWithFilters()
#23 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): BookController->run()
#24 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#25 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#26 C:\xampp\xampp\htdocs\mybook\index.php(13): CWebApplication->run()
REQUEST_URI=/mybook/index.php?r=book/index
in C:\xampp\xampp\htdocs\mybook\protected\views\book\_view.php (11)
in C:\xampp\xampp\htdocs\mybook\protected\views\book\index.php (17)
in C:\xampp\xampp\htdocs\mybook\protected\controllers\BookController.php (118)
2011/11/20 12:03:35 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mybookdb.{{users}}' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `{{users}}`.
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\models\User.php (28)
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\models\UserLogin.php (52)
2011/11/20 12:03:35 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{users}}" for active record class "User" cannot be found in the database.' in C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2276
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\xampp\htdocs\mybook\protected\modules\user\models\User.php(28): CActiveRecord::model('User')
#2 C:\xampp\xampp\htdocs\mybook\protected\modules\user\components\UserIdentity.php(27): User::model()
#3 C:\xampp\xampp\htdocs\mybook\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#4 C:\xampp\xampp\htdocs\yii\framework\validators\CInlineValidator.php(39): UserLogin->authenticate('password', Array)
#5 C:\xampp\xampp\htdocs\yii\framework\validators\CValidator.php(192): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#6 C:\xampp\xampp\htdocs\yii\framework\base\CModel.php(152): CValidator->validate(Object(UserLogin), NULL)
#7 C:\xampp\xampp\htdocs\mybook\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#8 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): LoginController->actionLogin()
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#11 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('')
#13 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('user/login')
#14 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#15 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#16 {main} REQUEST_URI=/mybook/index.php?r=user/login
2011/11/20 12:09:47 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mybookdb.{{profiles}}' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `{{profiles}}`.
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\controllers\ProfileController.php (19)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/20 12:09:47 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{profiles}}" for active record class "Profile" cannot be found in the database.' in C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2276
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(372): CActiveRecordMetaData->__construct(Object(Profile))
#1 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(221): CActiveRecord::model('Profile')
#2 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(51): CActiveFinder->buildJoinTree(Object(CJoinElement), 'profile')
#3 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(258): CActiveFinder->__construct(Object(User), 'profile')
#4 C:\xampp\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(127): CActiveRecord->getRelated('profile')
#5 C:\xampp\xampp\htdocs\mybook\protected\modules\user\controllers\ProfileController.php(19): CActiveRecord->__get('profile')
#6 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): ProfileController->actionProfile()
#7 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams(Array)
#8 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): CController->runAction(Object(CInlineAction))
#9 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): CController->run('')
#11 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController('user/profile')
#12 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#13 C:\xampp\xampp\htdocs\mybook\index.php(13): CApplication->run()
#14 {main} REQUEST_URI=/mybook/index.php?r=user/profile
2011/11/20 12:11:13 [error] [php] mail() [<a href='function.mail'>function.mail</a>]: Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\xampp\htdocs\mybook\protected\modules\user\UserModule.php:210)
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): RecoveryController->actionRecovery()
#1 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#2 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): RecoveryController->runAction()
#3 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): RecoveryController->runActionWithFilters()
#4 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): RecoveryController->run()
#5 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#6 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#7 C:\xampp\xampp\htdocs\mybook\index.php(13): CWebApplication->run()
REQUEST_URI=/mybook/index.php?r=user/recovery/recovery
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\UserModule.php (210)
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\controllers\RecoveryController.php (56)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
2011/11/20 12:14:23 [error] [php] mail() [<a href='function.mail'>function.mail</a>]: Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\xampp\htdocs\mybook\protected\modules\user\UserModule.php:210)
Stack trace:
#0 C:\xampp\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): RecoveryController->actionRecovery()
#1 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(300): CInlineAction->runWithParams()
#2 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(278): RecoveryController->runAction()
#3 C:\xampp\xampp\htdocs\yii\framework\web\CController.php(257): RecoveryController->runActionWithFilters()
#4 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(277): RecoveryController->run()
#5 C:\xampp\xampp\htdocs\yii\framework\web\CWebApplication.php(136): CWebApplication->runController()
#6 C:\xampp\xampp\htdocs\yii\framework\base\CApplication.php(158): CWebApplication->processRequest()
#7 C:\xampp\xampp\htdocs\mybook\index.php(13): CWebApplication->run()
REQUEST_URI=/mybook/index.php?r=user/recovery/recovery
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\UserModule.php (210)
in C:\xampp\xampp\htdocs\mybook\protected\modules\user\controllers\RecoveryController.php (56)
in C:\xampp\xampp\htdocs\mybook\index.php (13)
